//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastebookModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_PASTEBOOKEntities : DbContext
    {
        public DB_PASTEBOOKEntities()
            : base("name=DB_PASTEBOOKEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PB_COMMENT> PB_COMMENT { get; set; }
        public virtual DbSet<PB_FRIEND> PB_FRIEND { get; set; }
        public virtual DbSet<PB_LIKE> PB_LIKE { get; set; }
        public virtual DbSet<PB_NOTIFICATION> PB_NOTIFICATION { get; set; }
        public virtual DbSet<PB_POST> PB_POST { get; set; }
        public virtual DbSet<PB_REF_COUNTRY> PB_REF_COUNTRY { get; set; }
        public virtual DbSet<PB_USER> PB_USER { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
